version: '3.4'

services:
  cpp-master:
    container_name: cpp-master
    build: .
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./env/.env

  cmaker:
    container_name: cmake
    build: .
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - ./env/.env
    command:
      - /bin/bash
      - -c
      - |
        cd test_cmake/build
        cmake ..
        cmake --build .
        ./test_cmake

  # conan:
  #   container_name: conan
  #   build: .
  #   tty: true
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./env/.env
      # command:
      # - /bin/bash
      # - -c
      # - |
      #   cd test_cmake/build
      #   cmake ..
      #   cmake --build .
      #   ./test_cmake